### ISSUE TITLE
[Proposal]: Travix Logger to TypeScript

### ISSUE THREAD

**Issue by joanrm20** [Travix-International/travix-logger#22]
## Abstract
Currently, the library doesn't have support for TS projects. By migrating current library from JS to TypeScript we would be able to achieve:
- Use lib on future TS projects
- Take advantage of static typings helping the lib to scale easily 
- Make code more understandable 
- Align with future standards

## Proposal
- Add Tslint (TBD - discussion on PR)
- Remove Babel and Eslint (not required dependencies in general)
- Update lib to TS
- Update tests to TS
- Add npmrc to save strict dependencies
- Add CONTRIBUTION file specification

## Rationale
As an alternative approach we could add just required typings to the lib, but given the amount of code it might be worth it just move the library to TS

## Compatibility
- Increment a minor version 0.7.0
- The update should have no impact on current usages

**Comment by fahad19** [comment]
@joanrm20: do it 👍
